services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - backend


  usuarios-api:
    image: androidj5/usuarios-api:2
    container_name: usuarios_api
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8081:8080"
    networks:
      - backend

  restaurantes-api:
    build: .
    container_name: restaurantes_api
    depends_on:
      - postgres
      - usuarios-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - USUARIOS_API_URL=http://usuarios-api:8080/api/v1/usuarios
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend:
    driver: bridge